### ISSUE TITLE
Mobile Support?

### ISSUE THREAD

**Issue by zombiebaron** [Differential/polymer-demo#5]
I know this example is the bleeding edge of using web-components but does any of this run on mobile?

I tried adding the android and iOS platforms to the projects and running them and it looks like it ALMOST works but then flashes to just a white screen.

Any help on getting this to run as a mobile app would be AWESOME.

**Comment by zombiebaron** [comment]
Has there been any progress on this?  Or if you guys are having success with a mobile only app with polymer any information on getting started to remove the white screen issue would be awesome.

**Comment by spencercarli** [comment]
Not from me recently. I'm hoping to hop back into this soon and figure it out. 

Trying to figure out the differences between this app and the full mobile one we have.

**Comment by meteorpoly** [comment]
After removing and adding some of the packages it suddenly worked, you can get the project here:
https://github.com/meteorpoly/polymer-demo

**Comment by meteorpoly** [comment]
Maybe this small sample helps you get going:

[**polymerized-todo**](https://github.com/meteorpoly/polymerized-todo)

A small demo on how to use polymer elements in a Meteor project. The project has been tested on Android Tablets and Phones and in the Browser (Chrome / Firefox).

**Comment by spencercarli** [comment]
So it looks like 4a8af2bfd5033511d60c261aa150d7cf30a95d6e by @schnie fixed the original issue here.

I added a couple more things to get events working on iOS (not sure about Android). Want to give it a try?

**Comment by meteorpoly** [comment]
Thanks gents, I can confirm all working properly now on both iOS and Android.
